### ISSUE TITLE
No need check [Ryukyu: Avoid styling directly on HTML tag, define a class instead.] for keyframes 

### ISSUE THREAD

**Issue by phungrk** [riv-dev/code_checker#9]
@keyframes rip {
	0% {
		@include transform(scale(1),rotate(0.1deg));
		@include opacity(0);
		opacity: 0; 
	}
	30% {
		@include transform(scale(1.25),rotate(0.1deg));
		@include opacity(0.3);
	}
	100% {
		@include opacity(0);
		@include transform(scale(2),rotate(0.1deg));
	}
}

**Comment by kenryukyu** [comment]
Problem does not seem to occur anymore in newest version.  Please confirm
